# Generated by Django 4.2.2 on 2023-06-16 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tegs',
            new_name='tags',
        ),
    ]
